CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255) NOT NULL,
    email    VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE addresses
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    street  VARCHAR(255) NOT NULL,
    city    VARCHAR(255) NOT NULL,
    state   VARCHAR(255) NOT NULL,
    zip     VARCHAR(255) NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT pk_addresses PRIMARY KEY (id),
    CONSTRAINT fk_addresses_users
        FOREIGN KEY (user_id)
            REFERENCES users (id)
            ON DELETE NO ACTION
);

CREATE INDEX idx_addresses_user_id
    ON addresses (user_id);


CREATE TABLE categories
(
    id   SMALLINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (id)
);


CREATE TABLE products
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255) NOT NULL,
    price       DECIMAL(10, 2) NOT NULL,
    description TEXT NOT NULL,
    category_id SMALLINT NULL,
    CONSTRAINT pk_products PRIMARY KEY (id),
    CONSTRAINT fk_products_category
        FOREIGN KEY (category_id)
            REFERENCES categories (id)
            ON DELETE NO ACTION
);

CREATE INDEX idx_products_category_id
    ON products (category_id);


CREATE TABLE profiles
(
    id             BIGINT NOT NULL,
    bio            TEXT NULL,
    phone_number   VARCHAR(15) NULL,
    date_of_birth  DATE NULL,
    loyalty_points INTEGER DEFAULT 0 NULL,
    CONSTRAINT pk_profiles PRIMARY KEY (id),
    CONSTRAINT fk_profiles_users
        FOREIGN KEY (id)
            REFERENCES users (id)
            ON DELETE NO ACTION
);


CREATE TABLE wishlist
(
    product_id BIGINT NOT NULL,
    user_id    BIGINT NOT NULL,
    CONSTRAINT pk_wishlist PRIMARY KEY (product_id, user_id),
    CONSTRAINT fk_wishlist_product
        FOREIGN KEY (product_id)
            REFERENCES products (id)
            ON DELETE CASCADE,
    CONSTRAINT fk_wishlist_user
        FOREIGN KEY (user_id)
            REFERENCES users (id)
            ON DELETE NO ACTION
);

CREATE INDEX idx_wishlist_user_id
    ON wishlist (user_id);